Add a configuration option for inverted mouse wheel zoom
DigitalExtinction/Game pull request #487
Opened 2023-06-11 22:44 UTC by JackCrumpLeys

#479

2023-06-11 22:45 UTC, JackCrumpLeys commented on crates/camera/src/camera.rs
> +        self.0 = (if conf.scroll_inverted() {
Is this the best place for the logic?

2023-06-12 07:02 UTC, Indy2222 commented on crates/camera/src/camera.rs
> +        self.0 = (if conf.scroll_inverted() {
I think so.

2023-06-12 07:03 UTC, Indy2222 requested changes
Please update the documentation as part of the implementation commits. Otherwise LGTM.

2023-06-12 09:43 UTC, Indy2222 reviewed
Please squash the two commits and add `Closes #479.` to commit description. Otherwise LGTM.

2023-06-13 05:51 UTC, Indy2222 approved these changes

2023-06-13 07:24 UTC, merged