add audio config, closes #519.
DigitalExtinction/Game pull request #521
Opened 2023-06-18 03:49 UTC by JackCrumpLeys

closes #519.

2023-06-18 08:58 UTC, Indy2222 requested changes
I had only a few minor comments on the code.

One comment **unrelated** to this PR: Config properties are `pub` and thus can not just be accessed but also changed from anywhere in the code.

I think that properties should be accessible only via getter methods so it is not possible to change them. Once configuration changing is to be implemented, it should be done via newly introduced setters, because:

* we could make it more defensive and assert that the new value is valid,
* and we could add any custom code tracking what was changed or cascading / propagating changes to related values if necessary.

2023-06-18 08:58 UTC, Indy2222 commented on crates/audio/Cargo.toml
> +de_conf.workspace = true
Please sort dependencies alphabetically.

2023-06-18 08:58 UTC, Indy2222 commented on crates/conf/src/conf.rs
> +    #[ensure(*music_volume >= 0., "`music_volume` must be greater than 0.0.")]
* I would enforce that it is strictly larger than `0.0`. Alternatively, get rid of `music_enabled` and interpret `0.0` as disabled.
* Ensure that it is `<= 1.`.

2023-06-18 08:58 UTC, Indy2222 commented on crates/conf/src/conf.rs
> +    /// Whether music is enabled.
Please remove this doc comments, they just repeat name of the methods.

2023-06-23 11:02 UTC, Indy2222 commented
I forgot to mention it the last time: please update the docs/, there is a page dedicated to the configuration.

2023-06-23 11:06 UTC, Indy2222 commented
I created #537 so such changes get easier in the future.

2023-06-24 21:27 UTC, Indy2222 commented
Sorry, this has happen in the meantime #542. Should be easy to fix.

2023-06-24 22:47 UTC, JackCrumpLeys commented
> Sorry, this has happen in the meantime #542. Should be easy to fix.

fixed now

2023-06-25 07:03 UTC, Indy2222 requested changes

2023-06-25 07:03 UTC, Indy2222 commented on docs/src/conf.md
> +    number between `0.0` and `1.0`. If set to 0 music will not play.
Please add a new line at the end of file.

2023-06-25 07:24 UTC, Indy2222 approved these changes

2023-06-25 07:42 UTC, Indy2222 approved these changes

2023-06-25 07:43 UTC, Indy2222 approved these changes

2023-06-25 07:59 UTC, merged